import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Toaster } from 'sonner';
import './globals.css';
import Navbar from '../widgets/navbar/Navbar';
import Bootstrapper from '../widgets/bootstrapper/bootstrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full h-screen antialiased`}
    >
      <body className="h-screen w-full overflow-hidden flex flex-col">
        <Bootstrapper />
        <Navbar />
        <div className="p-4 flex flex-col flex-grow h-0">
          {children}
          <Toaster visibleToasts={5} position="top-right" />
        </div>
      </body>
    </html>
  );
}
